/* =========================================================
   ENGLISH B2 PREP - DICCIONARIO DE PALABRAS
   Al tocar/arrastrar una palabra en las explicaciones se
   muestra: traducción + ejemplo.
   ========================================================= */

const DICT = {
  /* --- gramática --- */
  'tense': { es: 'tiempo verbal', ex: 'The present tense is used for habits.' },
  'present': { es: 'presente', ex: 'I work every day. (present)' },
  'past': { es: 'pasado', ex: 'I worked yesterday. (past)' },
  'future': { es: 'futuro', ex: 'I will work tomorrow. (future)' },
  'habit': { es: 'hábito / costumbre', ex: 'Exercising is a good habit.' },
  'fact': { es: 'hecho', ex: 'It is a fact that water boils at 100°C.' },
  'schedule': { es: 'horario / programa', ex: 'The train schedule is on the wall.' },
  'temporary': { es: 'temporal / provisional', ex: 'This is a temporary job.' },
  'experience': { es: 'experiencia', ex: 'She has a lot of experience.' },
  'recent': { es: 'reciente', ex: 'Have you seen the recent news?' },
  'perfect': { es: 'perfecto', ex: 'The present perfect connects past and now.' },
  'continuous': { es: 'continuo / progresivo', ex: 'We use the continuous for actions in progress.' },
  'condition': { es: 'condición', ex: 'A condition must be met first.' },
  'hypothetical': { es: 'hipotético', ex: 'A hypothetical situation is imaginary.' },
  'passive': { es: 'pasivo / pasiva', ex: 'The passive focuses on the action.' },
  'active': { es: 'activo / activa', ex: 'The active voice is more direct.' },
  'deduction': { es: 'deducción', ex: 'This is my deduction from the evidence.' },
  'certain': { es: 'seguro / cierto', ex: 'I am certain that I am right.' },
  'possibility': { es: 'posibilidad', ex: 'There is a possibility of rain.' },
  'report': { es: 'informar / reportar', ex: 'Please report the results.' },
  'order': { es: 'orden / mandato', ex: 'He gave me an order to leave.' },
  'clause': { es: 'cláusula / oración', ex: 'A relative clause adds information.' },
  'relative': { es: 'relativo (pronombre)', ex: 'Who, which and that are relative pronouns.' },
  'phrasal': { es: 'frase verbal (phrasal verb)', ex: 'Phrasal verbs combine a verb and a particle.' },
  'gerund': { es: 'gerundio (forma -ing)', ex: 'A gerund is the -ing form of a verb.' },
  'infinitive': { es: 'infinitivo (to + verbo)', ex: 'The infinitive is to + the base verb.' },
  'connector': { es: 'conector / palabra de enlace', ex: 'However is a common connector.' },
  'cohesion': { es: 'cohesión', ex: 'Connectors improve the cohesion of a text.' },
  'comparative': { es: 'comparativo', ex: '"Bigger" is a comparative form.' },
  'superlative': { es: 'superlativo', ex: '"The biggest" is a superlative form.' },
  'expression': { es: 'expresión', ex: 'That is a very common expression.' },
  'idiom': { es: 'modismo / expresión idiomática', ex: 'An idiom is not literal.' },
  'wish': { es: 'desear / ojalá', ex: 'I wish I had more time.' },
  'causative': { es: 'causativo', ex: 'In the causative, you arrange for something.' },
  'strategy': { es: 'estrategia', ex: 'Good strategy is key in exams.' },
  'skimming': { es: 'lectura rápida para la idea general', ex: 'Skimming gives you the main idea.' },
  'scanning': { es: 'lectura de búsqueda de datos', ex: 'Scanning finds specific information.' },
  'gist': { es: 'idea general / lo esencial', ex: 'Get the gist of the text first.' },
  'detail': { es: 'detalle', ex: 'Pay attention to the small details.' },
  'announcement': { es: 'anuncio / aviso', ex: 'Listen to this announcement.' },
  'lecture': { es: 'conferencia / clase magistral', ex: 'The professor gave a lecture.' },

  /* --- vocabulario común --- */
  'achievement': { es: 'logro', ex: 'Winning the prize was a great achievement.' },
  'improve': { es: 'mejorar', ex: 'I want to improve my English.' },
  'improvement': { es: 'mejora', ex: 'There has been a big improvement.' },
  'avoid': { es: 'evitar', ex: 'Try to avoid mistakes in spelling.' },
  'benefit': { es: 'beneficio', ex: 'Exercise has many benefits.' },
  'challenge': { es: 'desafío / reto', ex: 'Learning a language is a challenge.' },
  'confident': { es: 'seguro / con confianza', ex: 'Be confident when you speak.' },
  'confidence': { es: 'confianza', ex: 'Speaking helps build confidence.' },
  'deadline': { es: 'fecha límite / plazo', ex: 'The deadline is on Friday.' },
  'degree': { es: 'título universitario', ex: 'She has a degree in history.' },
  'exam': { es: 'examen', ex: 'The exam is next week.' },
  'apply': { es: 'solicitar / aplicar', ex: 'I will apply for that job.' },
  'colleague': { es: 'compañero de trabajo', ex: 'My colleague helped me.' },
  'salary': { es: 'salario', ex: 'The salary is good.' },
  'promotion': { es: 'ascenso / promoción', ex: 'She got a promotion at work.' },
  'resign': { es: 'renunciar', ex: 'He resigned from his job.' },
  'pollution': { es: 'contaminación', ex: 'Pollution harms the environment.' },
  'environment': { es: 'medio ambiente / entorno', ex: 'We must protect the environment.' },
  'renewable': { es: 'renovable', ex: 'Solar energy is renewable.' },
  'sustainable': { es: 'sostenible', ex: 'Living sustainably helps the planet.' },
  'lifelong': { es: 'durante toda la vida', ex: 'Lifelong learning keeps your mind active.' },
  'flexible': { es: 'flexible', ex: 'My work schedule is flexible.' },
  'efficient': { es: 'eficiente', ex: 'Renewable energy is very efficient.' },
  'generation': { es: 'generación', ex: 'Every generation faces new challenges.' },
  'obvious': { es: 'obvio / evidente', ex: 'The answer was obvious.' },
  'essential': { es: 'esencial / imprescindible', ex: 'Sleep is essential.' },
  'require': { es: 'requerir / necesitar', ex: 'This job requires experience.' },
  'appropriate': { es: 'apropiado / adecuado', ex: 'This is an appropriate time.' },
  'available': { es: 'disponible', ex: 'The course is available online.' },
  'provide': { es: 'proporcionar', ex: 'The guide provides useful tips.' },
  'trend': { es: 'tendencia', ex: 'There is a growing trend.' },
  'isolated': { es: 'aislado', ex: 'Remote workers can feel isolated.' },
  'commute': { es: 'desplazarse al trabajo', ex: 'My commute takes one hour.' },
  'productivity': { es: 'productividad', ex: 'Teams measure their productivity.' },
  'livelihood': { es: 'medio de vida', ex: 'Farming is their livelihood.' },
  'revolutionise': { es: 'revolucionar', ex: 'The internet revolutionised work.' },
  'maintenance': { es: 'mantenimiento', ex: 'The lift is under maintenance.' },
  'suspend': { es: 'suspender / interrumpir', ex: 'The service was suspended.' },
  'forecast': { es: 'pronóstico', ex: 'The weather forecast says snow.' },
  'conference': { es: 'conferencia', ex: 'She attended a conference.' },
  'workshop': { es: 'taller', ex: 'The workshop is very practical.' },
  'seminar': { es: 'seminario', ex: 'He gave a seminar on writing.' },
  'audience': { es: 'audiencia / público', ex: 'The audience applauded.' },
  'attendees': { es: 'asistentes', ex: 'All attendees received a badge.' },
  'policy': { es: 'política / normativa', ex: 'The company policy is strict.' },
  'evidence': { es: 'evidencia', ex: 'There is evidence of climate change.' },
  'scientific': { es: 'científico', ex: 'This is a scientific study.' },
  'process': { es: 'proceso', ex: 'The learning process takes time.' },
  'negotiate': { es: 'negociar', ex: 'They negotiated a better salary.' },
  'regarding': { es: 'en cuanto a / respecto a', ex: 'Regarding your question, yes.' },
  'despite': { es: 'a pesar de', ex: 'Despite the rain, we went out.' },
  'although': { es: 'aunque', ex: 'Although it rained, we went out.' },
  'however': { es: 'sin embargo', ex: 'It was late; however, we stayed.' },
  'therefore': { es: 'por lo tanto', ex: 'I was tired, therefore I slept.' },
  'moreover': { es: 'además', ex: 'Moreover, it is cheap.' },
  'furthermore': { es: 'además', ex: 'Furthermore, we need more staff.' },
  'consequently': { es: 'en consecuencia', ex: 'It rained; consequently, the game was off.' },
  'eventually': { es: 'finalmente / al final', ex: 'Eventually, he succeeded.' },
  'obviously': { es: 'obviamente', ex: 'Obviously, you must practise.' },
  'surprisingly': { es: 'sorprendentemente', ex: 'Surprisingly, it was easy.' },
  'frequently': { es: 'frecuentemente', ex: 'I frequently review my notes.' },
  'occasionally': { es: 'ocasionalmente / de vez en cuando', ex: 'I occasionally go running.' },
  'recently': { es: 'recientemente', ex: 'I recently started a new job.' }
};
